# Generated by Django 5.2 on 2025-05-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutoSolidare', '0005_apadrinhados_foto_para_padrinho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padrinho',
            name='area_escolar_outro',
        ),
        migrations.RemoveField(
            model_name='padrinho',
            name='estilo_vida_outro',
        ),
        migrations.RemoveField(
            model_name='padrinho',
            name='extra_outro',
        ),
        migrations.RemoveField(
            model_name='padrinho',
            name='inspiracao_outro',
        ),
        migrations.RemoveField(
            model_name='padrinho',
            name='tempo_livre_outro',
        ),
        migrations.RemoveField(
            model_name='padrinho',
            name='valor_representa_outro',
        ),
    ]
