# Generated by Django 5.2 on 2025-05-18 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutoSolidare', '0006_remove_padrinho_area_escolar_outro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apadrinhados',
            old_name='estilo_vida',
            new_name='hobby',
        ),
        migrations.RenameField(
            model_name='apadrinhados',
            old_name='extra',
            new_name='profissao_desejada',
        ),
        migrations.RenameField(
            model_name='apadrinhados',
            old_name='tempo_livre',
            new_name='valores',
        ),
        migrations.RenameField(
            model_name='padrinho',
            old_name='estilo_vida',
            new_name='hobby',
        ),
        migrations.RenameField(
            model_name='padrinho',
            old_name='extra',
            new_name='inspiracoes',
        ),
        migrations.RenameField(
            model_name='padrinho',
            old_name='inspiracao',
            new_name='profissao_atual',
        ),
        migrations.RenameField(
            model_name='padrinho',
            old_name='tempo_livre',
            new_name='profissao_desejada_quando_crianca',
        ),
        migrations.RenameField(
            model_name='padrinho',
            old_name='valor_representa',
            new_name='valores',
        ),
        migrations.RemoveField(
            model_name='apadrinhados',
            name='palavras_chave',
        ),
        migrations.RemoveField(
            model_name='apadrinhados',
            name='valor_representa',
        ),
    ]
