# Generated by Django 5.2 on 2025-05-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutoSolidare', '0007_rename_estilo_vida_apadrinhados_hobby_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apadrinhados',
            old_name='inspiracao',
            new_name='inspiracoes',
        ),
    ]
