# Generated by Django 5.2 on 2025-05-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutoSolidare', '0008_rename_inspiracao_apadrinhados_inspiracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='padrinho',
            name='foto',
            field=models.ImageField(default='sem foto', upload_to='fotos/'),
            preserve_default=False,
        ),
    ]
